apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ .Chart.Name }}-auth-policy
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "splunk.labels" . | nindent 4 }}
spec:
  action: ALLOW
  rules:
  - {}