image:
  name: sonarqube
  tag: community
  imagePullPolicy: Always

namespace: sonarqube
replicas: 1

port:
  containerPort: 9000
  protocol: TCP

secretName: psql-settings

livenessProbe:
  httpGet: 
    path: /healthz
    port: 9000
  initialDelaySeconds: 60
  timeoutSeconds: 5
readinessProbe:
  httpGet: 
    path: /healthz
    port: 9000
  initialDelaySeconds: 60
  timeoutSeconds: 5

resources:
  limits:
    cpu: 1
    memory: 2.5Gi
  requests:
    cpu: 250m
    memory: 500Mi

localDevelopment: 
  development: true
  port: 30080
  type: NodePort


db:
  fqdn: jdbc:postgresql://postgresql.postgres.svc.cluster.local:5432/