apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "jenkins.labels" . | nindent 4 }}
data:
  JENKINS_HOME: /var/jenkins_home
  JAVA_OPTS: -Xmx8192m