apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.port.containerPort }}
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-config
        livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | nindent 12 }}
        ports:
          - name: http
            containerPort: {{ .Values.port.containerPort }}
            protocol: {{ .Values.port.protocol }}
          - name: another-port
            containerPort: {{ .Values.port.anotherPort }}
            protocol: {{ .Values.port.protocol }}
        resources:
{{ toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: {{ .Chart.Name }}-volumes
          mountPath: {{ .Values.hostPath }}
      volumes:
      - name: {{ .Chart.Name }}-volumes
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-home-pvc