apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-home-pv
  namespace: {{ .Values.namespace }}
  labels:
    usage: {{ .Chart.Name }}-shared-deployement
spec:
  storageClassName:  default
  capacity:
    storage: 3Gi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.hostPath }}