apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ .Chart.Name }}-svc-https
  namespace: {{ .Values.namespace }}
spec:
  hosts:
  - {{ .Values.externalUrl.updateJenkins }}
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS