image:
  name: splunk/splunk
  tag: 8.2
  imagePullPolicy: Always

namespace: splunk
replicas: 1

port:
  containerPort: 8000
  protocol: TCP

secretName: splunk-settings

livenessProbe:
  httpGet: 
    path: /healthz
    port: 8000
  initialDelaySeconds: 60
  timeoutSeconds: 5
readinessProbe:
  httpGet: 
    path: /healthz
    port: 8000
  initialDelaySeconds: 60
  timeoutSeconds: 5

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 500Mi

localDevelopment: 
  development: true
  port: 30081
  type: NodePort

splunk:
  agreeMent: "--accept-license"