apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.port.containerPort }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretName }}
        env:
        - name: SONAR_JDBC_URL
          value: {{ .Values.db.fqdn }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | nindent 12 }}
        ports:
          - name: http
            containerPort: {{ .Values.port.containerPort }}
            protocol: {{ .Values.port.protocol }}
        resources:
{{ toYaml .Values.resources | nindent 12 }}
