apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - protocol: {{ .Values.port.protocol }}
    targetPort: {{ .Values.port.containerPort }}
    port: {{ .Values.port.containerPort }}
    